pipeline {
    
    agent {
        docker {
            image 'maven:3.9.8-sapmachine-21'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    stages {
        stage ("build") {
            when {
                changeset "**/worker/**"
            }
            steps{
                echo 'Compiling worker app'
                dir ('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage ("test") {
            when {
                changeset "**/worker/**"
            }
            steps{
                echo 'Running Unit Tests on worker app'
                dir ('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage ("package") {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Packaging worker app into a jar file'
                dir ('worker') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }

    post {
        always {
            echo 'The job is complete.'
            slackSend (channel: "#ci-cd-jenkins", message: "Build Finished: ${env.JOB_NAME} ${env.BUILD_NUMBER}")
        }
        failure{
            slackSend (channel: "#ci-cd-jenkins", message: "Build Failed: ${env.JOB_NAME} ${env.BUILD_NUMBER}")
        }
        
        success{
            slackSend (channel: "#ci-cd-jenkins", message: "Build Success: ${env.JOB_NAME} ${env.BUILD_NUMBER}")
        }
    }
}
